version: '3.8'

services:
  # Main Application Service (Frontend + Backend)
  app:
    build: .
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET:-your-secure-jwt-secret-key}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-your-32-byte-encryption-key}
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-medflect_ai}
      - GROQ_API_KEY=${GROQ_API_KEY:-your-groq-api-key}
      - GROQ_BASE_URL=${GROQ_BASE_URL:-https://api.groq.com/openai/v1}
      - GROQ_MODEL=${GROQ_MODEL:-groq/deepseek-r1-distill-llama-70b}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - medflect-network
    healthcheck:
      test: ["CMD", "node", "./healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-medflect_ai}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-medflect_ai}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - medflect-network

  # pgAdmin (Database Management)
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - db
    networks:
      - medflect-network

volumes:
  postgres_data:

networks:
  medflect-network:
    driver: bridge
