services:
  - type: web
    name: medflectai-backend
    env: node
    buildCommand: npm install
    startCommand: npm run render-start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    plan: free
