services:
  - type: web
    name: MedFlectAInew1
    env: node
    buildCommand: npm install && cd client && npm install && cd ..
    startCommand: ./render-start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GROQ_BASE_URL
        value: your_groq_base_url
      - key: GROQ_API_KEY
        value: your_groq_api_key
      - key: GROQ_MODEL
        value: groq/deepseek-r1-distill-llama-70b
      - key: VITE_API_BASE
        value: https://medflectainew1.onrender.com
      - key: JWT_SECRET
        value: your-secure-jwt-secret-key
      - key: CORS_ORIGIN
        value: https://your-vercel-app.vercel.app
      - key: DATABASE_URL
        value: your_database_connection_string
    plan: free
