services:
  - type: web
    name: medflectai-backend
    env: node
    buildCommand: npm install && cd client && npm install && cd ..
    startCommand: ./render-start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    plan: free
